"use client"

import { useState, useEffect } from "react"
import { Card, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { ArrowLeft, Calculator, FileText, ChevronRight, BookOpen } from "lucide-react"
import Link from "next/link"
import { useLanguage } from "@/components/language-provider"
import { MathDisplay } from "@/components/math-display"

export default function SurfaceAreaRevolutionPage() {
  const { language } = useLanguage()

  // Content for both languages
  const content = {
    en: {
      title: "Surface Area of Solids of Revolution",
      subtitle: "Calculate the surface area generated by revolving a curve around an axis",
      backLink: "Back to Applications of Integral Calculus",
      introduction:
        "When a curve is revolved around an axis, it generates a three-dimensional surface. The surface area of this solid of revolution can be calculated using integral calculus, providing a powerful tool for solving problems in engineering, physics, and design.",
      formula: {
        title: "Surface Area Formula",
        description:
          "The surface area of a solid of revolution can be calculated using the following formulas, depending on the axis of rotation:",
        xAxis: "For rotation around the x-axis:",
        xAxisFormula: "S = 2\\pi \\int_{a}^{b} f(x) \\sqrt{1 + [f'(x)]^2} \\, dx",
        yAxis: "For rotation around the y-axis:",
        yAxisFormula: "S = 2\\pi \\int_{c}^{d} x \\sqrt{1 + [g'(y)]^2} \\, dy",
        where: "where:",
        whereDescription: [
          "f(x) is the function being revolved",
          "f'(x) is the derivative of the function",
          "g(y) is the function expressed in terms of y (when rotating around the y-axis)",
          "g'(y) is the derivative of g(y)",
          "[a, b] or [c, d] are the limits of integration",
        ],
      },
      example: {
        title: "Example",
        problem:
          "Find the surface area of the solid formed by revolving the curve y = x² from x = 0 to x = 2 around the x-axis.",
        solution: {
          title: "Solution:",
          steps: [
            {
              text: "1. Identify the function and its derivative:",
              formula: "f(x) = x^2, \\quad f'(x) = 2x"
            },
            {
              text: "2. Substitute into the surface area formula for rotation around the x-axis:",
              formula: "S = 2\\pi \\int_{0}^{2} x^2 \\sqrt{1 + (2x)^2} \\, dx = 2\\pi \\int_{0}^{2} x^2 \\sqrt{1 + 4x^2} \\, dx"
            },
            {
              text: "3. This integral is challenging to evaluate directly. We can use substitution:",
              formula: "\\text{Let } u = 1 + 4x^2, \\text{ then } du = 8x \\, dx \\text{ or } dx = \\frac{du}{8x}"
            },
            {
              text: "4. When x = 0, u = 1; when x = 2, u = 17. Rewriting the integral:",
              formula: "S = 2\\pi \\int_{1}^{17} x^2 \\sqrt{u} \\frac{du}{8x} = \\frac{\\pi}{4} \\int_{1}^{17} x \\sqrt{u} \\, du"
            },
            {
              text: "5. Since u = 1 + 4x², we have x = \\sqrt{\\frac{u-1}{4}} and x² = \\frac{u-1}{4}:",
              formula: "S = \\frac{\\pi}{4} \\int_{1}^{17} \\sqrt{\\frac{u-1}{4}} \\sqrt{u} \\, du = \\frac{\\pi}{8} \\int_{1}^{17} \\sqrt{u(u-1)} \\, du"
            },
            {
              text: "6. This integral can be evaluated using advanced techniques, resulting in:",
              formula: "S = \\frac{\\pi}{12}\\left[\\sqrt{u(u-1)}(2u-1) + \\sinh^{-1}\\sqrt{u-1}\\right]_{1}^{17}"
            },
            {
              text: "7. Evaluating at the limits and simplifying:",
              formula: "S = \\frac{\\pi}{12}\\left[\\sqrt{17 \\cdot 16}(34-1) + \\sinh^{-1}\\sqrt{16} - \\sqrt{1 \\cdot 0}(2-1) - \\sinh^{-1}\\sqrt{0}\\right]"
            },
            {
              text: "8. Further simplification:",
              formula: "S = \\frac{\\pi}{12}\\left[16.5 \\cdot 33 + \\sinh^{-1}(4) - 0 - 0\\right] \\approx \\frac{\\pi}{12}[544.5 + 2.094] \\approx 143.6\\pi \\approx 451.1 \\text{ square units}"
            }
          ]
        },
      },
      applications: {
        title: "Applications",
        description: "The surface area of solids of revolution has numerous applications:",
        list: [
          "Engineering: Designing containers, tanks, and vessels",
          "Manufacturing: Calculating material requirements for curved surfaces",
          "Physics: Analyzing fluid flow over curved surfaces",
          "Architecture: Designing domes and curved structures",
        ],
      },
      relatedTopics: [
        { name: "Volume of Solids of Revolution", path: "/topics/mathematics/integral-calculus-applications/volume-solids-revolution" },
        { name: "Area Under a Curve", path: "/topics/mathematics/integral-calculus-applications/area-under-curve" },
        { name: "Area Between Curves", path: "/topics/mathematics/integral-calculus-applications/area-between-curves" },
        { name: "Integration Techniques", path: "/topics/mathematics/integral-calculus/integration-methods/integration-by-substitution" },
      ],
      resources: [
        {
          title: "Solved Problems",
          description: "Practice with step-by-step solutions",
          link: "/resources/solved-problems?topic=surface-area-revolution",
          linkText: "View problems",
        },
        {
          title: "Interactive Calculator",
          description: "Calculate surface areas with our tool",
          link: "/resources/tools/surface-area-calculator",
          linkText: "Use calculator",
        },
        {
          title: "Recommended Reading",
          description: "Books and articles on integral applications",
          link: "/resources/bibliography?topic=integral-applications",
          linkText: "View bibliography",
        },
      ],
    },
    es: {
      title: "Área de Superficie de Sólidos de Revolución",
      subtitle: "Calcula el área de superficie generada al girar una curva alrededor de un eje",
      backLink: "Volver a Aplicaciones",
      introduction:
        "Cuando una curva gira alrededor de un eje, genera una superficie tridimensional. El área de superficie de este sólido de revolución puede calcularse utilizando cálculo integral, proporcionando una herramienta poderosa para resolver problemas en ingeniería, física y diseño.",
      formula: {
        title: "Fórmula del Área de Superficie",
        description:
          "El área de superficie de un sólido de revolución puede calcularse utilizando las siguientes fórmulas, dependiendo del eje de rotación:",
        xAxis: "Para rotación alrededor del eje x:",
        xAxisFormula: "S = 2\\pi \\int_{a}^{b} f(x) \\sqrt{1 + [f'(x)]^2} \\, dx",
        yAxis: "Para rotación alrededor del eje y:",
        yAxisFormula: "S = 2\\pi \\int_{c}^{d} x \\sqrt{1 + [g'(y)]^2} \\, dy",
        where: "donde:",
        whereDescription: [
          "f(x) es la función que se está girando",
          "f'(x) es la derivada de la función",
          "g(y) es la función expresada en términos de y (cuando se gira alrededor del eje y)",
          "g'(y) es la derivada de g(y)",
          "[a, b] o [c, d] son los límites de integración",
        ],
      },
      example: {
        title: "Ejemplo",
        problem:
          "Encuentra el área de superficie del sólido formado al girar la curva y = x² desde x = 0 hasta x = 2 alrededor del eje x.",
        solution: {
          title: "Solución:",
          steps: [
            {
              text: "1. Identifica la función y su derivada:",
              formula: "f(x) = x^2, \\quad f'(x) = 2x"
            },
            {
              text: "2. Sustituye en la fórmula del área de superficie para rotación alrededor del eje x:",
              formula: "S = 2\\pi \\int_{0}^{2} x^2 \\sqrt{1 + (2x)^2} \\, dx = 2\\pi \\int_{0}^{2} x^2 \\sqrt{1 + 4x^2} \\, dx"
            },
            {
              text: "3. Esta integral es difícil de evaluar directamente. Podemos usar sustitución:",
              formula: "\\text{Sea } u = 1 + 4x^2, \\text{ entonces } du = 8x \\, dx \\text{ o } dx = \\frac{du}{8x}"
            },
            {
              text: "4. Cuando x = 0, u = 1; cuando x = 2, u = 17. Reescribiendo la integral:",
              formula: "S = 2\\pi \\int_{1}^{17} x^2 \\sqrt{u} \\frac{du}{8x} = \\frac{\\pi}{4} \\int_{1}^{17} x \\sqrt{u} \\, du"
            },
            {
              text: "5. Como u = 1 + 4x², tenemos x = \\sqrt{\\frac{u-1}{4}} y x² = \\frac{u-1}{4}:",
              formula: "S = \\frac{\\pi}{4} \\int_{1}^{17} \\sqrt{\\frac{u-1}{4}} \\sqrt{u} \\, du = \\frac{\\pi}{8} \\int_{1}^{17} \\sqrt{u(u-1)} \\, du"
            },
            {
              text: "6. Esta integral puede evaluarse utilizando técnicas avanzadas, resultando en:",
              formula: "S = \\frac{\\pi}{12}\\left[\\sqrt{u(u-1)}(2u-1) + \\sinh^{-1}\\sqrt{u-1}\\right]_{1}^{17}"
            },
            {
              text: "7. Evaluando en los límites y simplificando:",
              formula: "S = \\frac{\\pi}{12}\\left[\\sqrt{17 \\cdot 16}(34-1) + \\sinh^{-1}\\sqrt{16} - \\sqrt{1 \\cdot 0}(2-1) - \\sinh^{-1}\\sqrt{0}\\right]"
            },
            {
              text: "8. Simplificación adicional:",
              formula: "S = \\frac{\\pi}{12}\\left[16.5 \\cdot 33 + \\sinh^{-1}(4) - 0 - 0\\right] \\approx \\frac{\\pi}{12}[544.5 + 2.094] \\approx 143.6\\pi \\approx 451.1 \\text{ unidades cuadradas}"
            }
          ]
        },
      },
      applications: {
        title: "Aplicaciones",
        description: "El área de superficie de sólidos de revolución tiene numerosas aplicaciones:",
        list: [
          "Ingeniería: Diseño de contenedores, tanques y recipientes",
          "Fabricación: Cálculo de requisitos de material para superficies curvas",
          "Física: Análisis del flujo de fluidos sobre superficies curvas",
          "Arquitectura: Diseño de cúpulas y estructuras curvas",
        ],
      },
      relatedTopics: [
        { name: "Volumen de sólidos de revolución", path: "/topics/mathematics/integral-calculus-applications/volume-solids-revolution" },
        { name: "Área bajo una curva", path: "/topics/mathematics/integral-calculus-applications/area-under-curve" },
        { name: "Área entre curvas", path: "/topics/mathematics/integral-calculus-applications/area-between-curves" },
        { name: "Técnicas de integración", path: "/topics/mathematics/integral-calculus/integration-methods/integration-by-substitution" },
      ],
      resources: [
        {
          title: "Solved Problems",
          description: "Practice with step-by-step solutions",
          link: "/resources/solved-problems?topic=surface-area-revolution",
          linkText: "View problems",
        },
        {
          title: "Interactive Calculator",
          description: "Calculate surface areas with our tool",
          link: "/resources/tools/surface-area-calculator",
          linkText: "Use calculator",
        },
        {
          title: "Recommended Reading",
          description: "Books and articles on integral applications",
          link: "/resources/bibliography?topic=integral-applications",
          linkText: "View bibliography",
        },
      ],
    },
  }

  const currentContent = language === "es" ? content.es : content.en

  return (
    <div className="container py-12">
      {/* Breadcrumb Navigation */}
      <div className="flex items-center text-sm text-muted-foreground mb-6">
        <Link href="/" className="hover:text-foreground">
          {language === "es" ? "Inicio" : "Home"}
        </Link>
        <ChevronRight className="h-4 w-4 mx-1" />
        <Link href="/topics" className="hover:text-foreground">
          {language === "es" ? "Temas" : "Topics"}
        </Link>
        <ChevronRight className="h-4 w-4 mx-1" />
        <Link href="/topics/mathematics" className="hover:text-foreground">
          {language === "es" ? "Matemáticas" : "Mathematics"}
        </Link>
        <ChevronRight className="h-4 w-4 mx-1" />
        <Link href="/topics/mathematics/integral-calculus-applications" className="hover:text-foreground">
          {language === "es" ? "Aplicaciones del Cálculo Integral" : "Applications of Integral Calculus"}
        </Link>
        <ChevronRight className="h-4 w-4 mx-1" />
        <span className="text-foreground font-medium">{currentContent.title}</span>
      </div>

      {/* Page Header */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-8">
        <div>
          <h1 className="text-3xl font-bold tracking-tight mb-2">{currentContent.title}</h1>
          <p className="text-muted-foreground">{currentContent.subtitle}</p>
        </div>
        <Button variant="outline" size="sm" asChild>
          <Link href="/topics/mathematics/integral-calculus-applications" className="flex items-center">
            <ArrowLeft className="mr-2 h-4 w-4" />
            {currentContent.backLink}
          </Link>
        </Button>
      </div>

      {/* Main Content */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Main Content Column */}
        <div className="lg:col-span-2 space-y-8">
          {/* Introduction */}
          <div className="prose dark:prose-invert max-w-none">
            <p>{currentContent.introduction}</p>
          </div>

          {/* Formula Section */}
          <Card>
            <CardContent className="pt-6">
              <h2 className="text-2xl font-semibold mb-4">{currentContent.formula.title}</h2>
              <p className="mb-4">{currentContent.formula.description}</p>

              <div className="mb-4">
                <p className="font-medium mb-2">{currentContent.formula.xAxis}</p>
                <div className="flex justify-center my-4">
                  <MathDisplay math={currentContent.formula.xAxisFormula} />
                </div>
              </div>

              <div className="mb-4">
                <p className="font-medium mb-2">{currentContent.formula.yAxis}</p>
                <div className="flex justify-center my-4">
                  <MathDisplay math={currentContent.formula.yAxisFormula} />
                </div>
              </div>

              <div>
                <p className="font-medium mb-2">{currentContent.formula.where}</p>
                <ul className="list-disc pl-6 space-y-1">
                  {currentContent.formula.whereDescription.map((item, index) => (
                    <li key={index}>{item}</li>
                  ))}
                </ul>
              </div>
            </CardContent>
          </Card>

          {/* Example Section */}
          <Card>
            <CardContent className="pt-6">
              <h2 className="text-2xl font-semibold mb-4">{currentContent.example.title}</h2>
              <p className="mb-4 font-medium">{currentContent.example.problem}</p>

              <div>
                <p className="font-semibold mb-2">{currentContent.example.solution.title}</p>
                <div className="space-y-4">
                  {currentContent.example.solution.steps.map((step, index) => (
                    <div key={index}>
                      <p>{step.text}</p>
                      <div className="flex justify-center my-2">
                        <MathDisplay math={step.formula} />
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Applications Section */}
          <Card>
            <CardContent className="pt-6">
              <h2 className="text-2xl font-semibold mb-4">{currentContent.applications.title}</h2>
              <p className="mb-4">{currentContent.applications.description}</p>
              <ul className="list-disc pl-6 space-y-1">
                {currentContent.applications.list.map((item, index) => (
                  <li key={index}>{item}</li>
                ))}
              </ul>
            </CardContent>
          </Card>
        </div>

        {/* Sidebar Column */}
        <div className="space-y-6">
          {/* Table of Contents */}
          <Card>
            <CardContent className="pt-6">
              <h3 className="font-semibold mb-3">{language === "es" ? "En Esta Página" : "On This Page"}</h3>
              <ul className="space-y-2 text-sm">
                <li>
                  <a href="#formula" className="text-primary hover:underline">
                    {currentContent.formula.title}
                  </a>
                </li>
                <li>
                  <a href="#example" className="text-muted-foreground hover:text-primary">
                    {currentContent.example.title}
                  </a>
                </li>
                <li>
                  <a href="#applications" className="text-muted-foreground hover:text-primary">
                    {currentContent.applications.title}
                  </a>
                </li>
              </ul>
            </CardContent>
          </Card>

          {/* Related Topics */}
          <Card>
            <CardContent className="pt-6">
              <h3 className="font-semibold mb-3">{language === "es" ? "Temas Relacionados" : "Related Topics"}</h3>
              <ul className="space-y-2 text-sm">
                {currentContent.relatedTopics.map((topic, index) => (
                  <li key={index}>
                    <Link href={topic.path} className="text-primary hover:underline flex items-center">
                      <ChevronRight className="h-3 w-3 mr-1" />
                      {topic.name}
                    </Link>
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>

          {/* Resources */}
          <Card>
            <CardContent className="pt-6">
              <h3 className="font-semibold mb-3">
                {language === "es" ? "Recursos de Aprendizaje" : "Learning Resources"}
              </h3>

              <div className="space-y-4">
                {currentContent.resources.map((resource, index) => (
                  <div key={index} className="flex items-start gap-3">
                    <div className="bg-primary/10 p-2 rounded-md">
                      {index === 0 ? (
                        <FileText className="h-4 w-4 text-primary" />
                      ) : index === 1 ? (
                        <Calculator className="h-4 w-4 text-primary" />
                      ) : (
                        <BookOpen className="h-4 w-4 text-primary" />
                      )}
                    </div>
                    <div>
                      <h4 className="text-sm font-medium">{resource.title}</h4>
                      <p className="text-xs text-muted-foreground mb-1">{resource.description}</p>
                      <Link href={resource.link} className="text-xs text-primary hover:underline">
                        {resource.linkText}
                      </Link>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
