"use client"

import Link from "next/link"
import { ArrowLeft } from "lucide-react"
import { Button } from "@/components/ui/button"
import { useLanguage } from "@/components/language-provider"
import { MathDisplay } from "@/components/math-display"

export default function SurfaceAreaRevolutionPage() {
  const { language } = useLanguage()

  // Content for both languages
  const content = {
    en: {
      title: "Surface Area of Solids of Revolution",
      description: "Calculate the surface area generated by revolving a curve around an axis.",
      backLink: "Back to Applications",
      introduction:
        "When a curve is revolved around an axis, it generates a three-dimensional surface. The surface area of this solid of revolution can be calculated using integral calculus, providing a powerful tool for solving problems in engineering, physics, and design.",
      formula: {
        title: "Surface Area Formula",
        description:
          "The surface area of a solid of revolution can be calculated using the following formulas, depending on the axis of rotation:",
        xAxis: "For rotation around the x-axis:",
        xAxisFormula: "S = 2\\pi \\int_{a}^{b} f(x) \\sqrt{1 + [f'(x)]^2} \\, dx",
        yAxis: "For rotation around the y-axis:",
        yAxisFormula: "S = 2\\pi \\int_{c}^{d} x \\sqrt{1 + [g'(y)]^2} \\, dy",
        where: "where:",
        whereDescription: [
          "f(x) is the function being revolved",
          "f'(x) is the derivative of the function",
          "g(y) is the function expressed in terms of y (when rotating around the y-axis)",
          "g'(y) is the derivative of g(y)",
          "[a, b] or [c, d] are the limits of integration",
        ],
      },
      example: {
        title: "Example",
        problem:
          "Find the surface area of the solid formed by revolving the curve y = x² from x = 0 to x = 2 around the x-axis.",
        solution: {
          title: "Solution:",
          step1: "1. Identify the function and its derivative:",
          step1Formula: "f(x) = x^2, \\quad f'(x) = 2x",
          step2: "2. Substitute into the surface area formula for rotation around the x-axis:",
          step2Formula:
            "S = 2\\pi \\int_{0}^{2} x^2 \\sqrt{1 + (2x)^2} \\, dx = 2\\pi \\int_{0}^{2} x^2 \\sqrt{1 + 4x^2} \\, dx",
          step3: "3. This integral is challenging to evaluate directly. We can use substitution:",
          step3Formula: "\\text{Let } u = 1 + 4x^2, \\text{ then } du = 8x \\, dx \\text{ or } dx = \\frac{du}{8x}",
          step4: "4. When x = 0, u = 1; when x = 2, u = 17. Rewriting the integral:",
          step4Formula:
            "S = 2\\pi \\int_{1}^{17} x^2 \\sqrt{u} \\frac{du}{8x} = \\frac{\\pi}{4} \\int_{1}^{17} x \\sqrt{u} \\, du",
          step5: "5. Since u = 1 + 4x², we have x = \\sqrt{\\frac{u-1}{4}} and x² = \\frac{u-1}{4}:",
          step5Formula:
            "S = \\frac{\\pi}{4} \\int_{1}^{17} \\sqrt{\\frac{u-1}{4}} \\sqrt{u} \\, du = \\frac{\\pi}{8} \\int_{1}^{17} \\sqrt{u(u-1)} \\, du",
          step6: "6. This integral can be evaluated using advanced techniques, resulting in:",
          step6Formula: "S = \\frac{\\pi}{12}\\left[\\sqrt{u(u-1)}(2u-1) + \\sinh^{-1}\\sqrt{u-1}\\right]_{1}^{17}",
          step7: "7. Evaluating at the limits and simplifying:",
          step7Formula:
            "S = \\frac{\\pi}{12}\\left[\\sqrt{17 \\cdot 16}(34-1) + \\sinh^{-1}\\sqrt{16} - \\sqrt{1 \\cdot 0}(2-1) - \\sinh^{-1}\\sqrt{0}\\right]",
          step8: "8. Further simplification:",
          step8Formula:
            "S = \\frac{\\pi}{12}\\left[16.5 \\cdot 33 + \\sinh^{-1}(4) - 0 - 0\\right] \\approx \\frac{\\pi}{12}[544.5 + 2.094] \\approx 143.6\\pi \\approx 451.1 \\text{ square units}",
        },
      },
      applications: {
        title: "Applications",
        description: "The surface area of solids of revolution has numerous applications:",
        list: [
          "Engineering: Designing containers, tanks, and vessels",
          "Manufacturing: Calculating material requirements for curved surfaces",
          "Physics: Analyzing fluid flow over curved surfaces",
          "Architecture: Designing domes and curved structures",
        ],
      },
    },
    es: {
      title: "Área de Superficie de Sólidos de Revolución",
      description: "Calcula el área de superficie generada al girar una curva alrededor de un eje.",
      backLink: "Volver a Aplicaciones",
      introduction:
        "Cuando una curva gira alrededor de un eje, genera una superficie tridimensional. El área de superficie de este sólido de revolución puede calcularse utilizando cálculo integral, proporcionando una herramienta poderosa para resolver problemas en ingeniería, física y diseño.",
      formula: {
        title: "Fórmula del Área de Superficie",
        description:
          "El área de superficie de un sólido de revolución puede calcularse utilizando las siguientes fórmulas, dependiendo del eje de rotación:",
        xAxis: "Para rotación alrededor del eje x:",
        xAxisFormula: "S = 2\\pi \\int_{a}^{b} f(x) \\sqrt{1 + [f'(x)]^2} \\, dx",
        yAxis: "Para rotación alrededor del eje y:",
        yAxisFormula: "S = 2\\pi \\int_{c}^{d} x \\sqrt{1 + [g'(y)]^2} \\, dy",
        where: "donde:",
        whereDescription: [
          "f(x) es la función que se está girando",
          "f'(x) es la derivada de la función",
          "g(y) es la función expresada en términos de y (cuando se gira alrededor del eje y)",
          "g'(y) es la derivada de g(y)",
          "[a, b] o [c, d] son los límites de integración",
        ],
      },
      example: {
        title: "Ejemplo",
        problem:
          "Encuentra el área de superficie del sólido formado al girar la curva y = x² desde x = 0 hasta x = 2 alrededor del eje x.",
        solution: {
          title: "Solución:",
          step1: "1. Identifica la función y su derivada:",
          step1Formula: "f(x) = x^2, \\quad f'(x) = 2x",
          step2: "2. Sustituye en la fórmula del área de superficie para rotación alrededor del eje x:",
          step2Formula:
            "S = 2\\pi \\int_{0}^{2} x^2 \\sqrt{1 + (2x)^2} \\, dx = 2\\pi \\int_{0}^{2} x^2 \\sqrt{1 + 4x^2} \\, dx",
          step3: "3. Esta integral es difícil de evaluar directamente. Podemos usar sustitución:",
          step3Formula: "\\text{Sea } u = 1 + 4x^2, \\text{ entonces } du = 8x \\, dx \\text{ o } dx = \\frac{du}{8x}",
          step4: "4. Cuando x = 0, u = 1; cuando x = 2, u = 17. Reescribiendo la integral:",
          step4Formula:
            "S = 2\\pi \\int_{1}^{17} x^2 \\sqrt{u} \\frac{du}{8x} = \\frac{\\pi}{4} \\int_{1}^{17} x \\sqrt{u} \\, du",
          step5: "5. Como u = 1 + 4x², tenemos x = \\sqrt{\\frac{u-1}{4}} y x² = \\frac{u-1}{4}:",
          step5Formula:
            "S = \\frac{\\pi}{4} \\int_{1}^{17} \\sqrt{\\frac{u-1}{4}} \\sqrt{u} \\, du = \\frac{\\pi}{8} \\int_{1}^{17} \\sqrt{u(u-1)} \\, du",
          step6: "6. Esta integral puede evaluarse utilizando técnicas avanzadas, resultando en:",
          step6Formula: "S = \\frac{\\pi}{12}\\left[\\sqrt{u(u-1)}(2u-1) + \\sinh^{-1}\\sqrt{u-1}\\right]_{1}^{17}",
          step7: "7. Evaluando en los límites y simplificando:",
          step7Formula:
            "S = \\frac{\\pi}{12}\\left[\\sqrt{17 \\cdot 16}(34-1) + \\sinh^{-1}\\sqrt{16} - \\sqrt{1 \\cdot 0}(2-1) - \\sinh^{-1}\\sqrt{0}\\right]",
          step8: "8. Simplificación adicional:",
          step8Formula:
            "S = \\frac{\\pi}{12}\\left[16.5 \\cdot 33 + \\sinh^{-1}(4) - 0 - 0\\right] \\approx \\frac{\\pi}{12}[544.5 + 2.094] \\approx 143.6\\pi \\approx 451.1 \\text{ unidades cuadradas}",
        },
      },
      applications: {
        title: "Aplicaciones",
        description: "El área de superficie de sólidos de revolución tiene numerosas aplicaciones:",
        list: [
          "Ingeniería: Diseño de contenedores, tanques y recipientes",
          "Fabricación: Cálculo de requisitos de material para superficies curvas",
          "Física: Análisis del flujo de fluidos sobre superficies curvas",
          "Arquitectura: Diseño de cúpulas y estructuras curvas",
        ],
      },
    },
  }

  const currentContent = language === "es" ? content.es : content.en

  return (
    <div className="container py-8">
      <div className="flex justify-start mb-8">
        <Button variant="outline" asChild className="gap-1">
          <Link href="/topics/mathematics/integral-calculus-applications">
            <ArrowLeft className="h-4 w-4" />
            {currentContent.backLink}
          </Link>
        </Button>
      </div>

      <div className="space-y-8 max-w-4xl mx-auto">
        <div className="text-center">
          <h1 className="text-4xl font-bold mb-4">{currentContent.title}</h1>
          <p className="text-xl text-muted-foreground">{currentContent.description}</p>
        </div>

        <div>
          <p className="mb-6">{currentContent.introduction}</p>
        </div>

        <div className="bg-card p-6 rounded-lg border">
          <h2 className="text-2xl font-semibold mb-4">{currentContent.formula.title}</h2>
          <p className="mb-4">{currentContent.formula.description}</p>

          <div className="mb-4">
            <p className="font-medium mb-2">{currentContent.formula.xAxis}</p>
            <div className="flex justify-center my-4">
              <MathDisplay math={currentContent.formula.xAxisFormula} />
            </div>
          </div>

          <div className="mb-4">
            <p className="font-medium mb-2">{currentContent.formula.yAxis}</p>
            <div className="flex justify-center my-4">
              <MathDisplay math={currentContent.formula.yAxisFormula} />
            </div>
          </div>

          <div>
            <p className="font-medium mb-2">{currentContent.formula.where}</p>
            <ul className="list-disc pl-6 space-y-1">
              {currentContent.formula.whereDescription.map((item, index) => (
                <li key={index}>{item}</li>
              ))}
            </ul>
          </div>
        </div>

        <div className="bg-card p-6 rounded-lg border">
          <h2 className="text-2xl font-semibold mb-4">{currentContent.example.title}</h2>
          <p className="mb-4 font-medium">{currentContent.example.problem}</p>

          <div>
            <p className="font-semibold mb-2">{currentContent.example.solution.title}</p>

            <div className="space-y-4">
              <div>
                <p>{currentContent.example.solution.step1}</p>
                <div className="flex justify-center my-2">
                  <MathDisplay math={currentContent.example.solution.step1Formula} />
                </div>
              </div>

              <div>
                <p>{currentContent.example.solution.step2}</p>
                <div className="flex justify-center my-2">
                  <MathDisplay math={currentContent.example.solution.step2Formula} />
                </div>
              </div>

              <div>
                <p>{currentContent.example.solution.step3}</p>
                <div className="flex justify-center my-2">
                  <MathDisplay math={currentContent.example.solution.step3Formula} />
                </div>
              </div>

              <div>
                <p>{currentContent.example.solution.step4}</p>
                <div className="flex justify-center my-2">
                  <MathDisplay math={currentContent.example.solution.step4Formula} />
                </div>
              </div>

              <div>
                <p>{currentContent.example.solution.step5}</p>
                <div className="flex justify-center my-2">
                  <MathDisplay math={currentContent.example.solution.step5Formula} />
                </div>
              </div>

              <div>
                <p>{currentContent.example.solution.step6}</p>
                <div className="flex justify-center my-2">
                  <MathDisplay math={currentContent.example.solution.step6Formula} />
                </div>
              </div>

              <div>
                <p>{currentContent.example.solution.step7}</p>
                <div className="flex justify-center my-2">
                  <MathDisplay math={currentContent.example.solution.step7Formula} />
                </div>
              </div>

              <div>
                <p>{currentContent.example.solution.step8}</p>
                <div className="flex justify-center my-2">
                  <MathDisplay math={currentContent.example.solution.step8Formula} />
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="bg-card p-6 rounded-lg border">
          <h2 className="text-2xl font-semibold mb-4">{currentContent.applications.title}</h2>
          <p className="mb-4">{currentContent.applications.description}</p>
          <ul className="list-disc pl-6 space-y-1">
            {currentContent.applications.list.map((item, index) => (
              <li key={index}>{item}</li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  )
}
