"use client"

import Link from "next/link"
import { ArrowLeft } from "lucide-react"
import { Button } from "@/components/ui/button"
import { useLanguage } from "@/components/language-provider"
import { MathDisplay } from "@/components/math-display"

export default function PappusTheoremPage() {
  const { language } = useLanguage()

  // Content for both languages
  const content = {
    en: {
      title: "Pappus' Theorem",
      description: "Calculate volumes and surface areas using centroids of planar regions.",
      backLink: "Back to Applications",
      introduction:
        "Pappus' Theorem, named after the Greek mathematician Pappus of Alexandria, provides elegant formulas for calculating volumes and surface areas of solids of revolution using the concept of centroids. These theorems simplify complex calculations and offer powerful insights into the properties of three-dimensional objects.",
      firstTheorem: {
        title: "First Theorem of Pappus-Guldinus (Volume)",
        description:
          "The volume of a solid of revolution generated by rotating a plane figure around an external axis is equal to the product of the area of the figure and the distance traveled by its centroid during the rotation:",
        formula: "V = A \\cdot 2\\pi\\bar{d}",
        where: "where:",
        whereDescription: [
          "V is the volume of the solid of revolution",
          "A is the area of the plane figure being rotated",
          "\\bar{d} is the distance from the centroid of the figure to the axis of rotation",
        ],
      },
      secondTheorem: {
        title: "Second Theorem of Pappus-Guldinus (Surface Area)",
        description:
          "The surface area of a solid of revolution generated by rotating a plane curve around an external axis is equal to the product of the length of the curve and the distance traveled by its centroid during the rotation:",
        formula: "S = L \\cdot 2\\pi\\bar{d}",
        where: "where:",
        whereDescription: [
          "S is the surface area of the solid of revolution",
          "L is the length of the curve being rotated",
          "\\bar{d} is the distance from the centroid of the curve to the axis of rotation",
        ],
      },
      example: {
        title: "Example: Torus Volume",
        problem:
          "Calculate the volume of a torus (donut shape) with a circular cross-section of radius r = 2 units, where the distance from the center of the cross-section to the axis of rotation is R = 5 units.",
        solution: {
          title: "Solution:",
          step1: "1. Identify the plane figure and its area:",
          step1Description: "The plane figure is a circle with radius r = 2 units.",
          step1Formula: "A = \\pi r^2 = \\pi \\cdot 2^2 = 4\\pi \\text{ square units}",
          step2: "2. Identify the distance from the centroid to the axis of rotation:",
          step2Description:
            "The centroid of a circle is at its center, which is R = 5 units from the axis of rotation.",
          step2Formula: "\\bar{d} = R = 5 \\text{ units}",
          step3: "3. Apply the First Theorem of Pappus-Guldinus:",
          step3Formula: "V = A \\cdot 2\\pi\\bar{d} = 4\\pi \\cdot 2\\pi \\cdot 5 = 40\\pi^2 \\text{ cubic units}",
          step4: "4. Calculate the numerical value:",
          step4Formula: "V = 40\\pi^2 \\approx 40 \\cdot 9.87 \\approx 394.8 \\text{ cubic units}",
        },
      },
      applications: {
        title: "Applications",
        description: "Pappus' Theorem has numerous applications in mathematics, engineering, and physics:",
        list: [
          "Calculating volumes and surface areas of complex solids of revolution",
          "Designing and analyzing mechanical parts with rotational symmetry",
          "Simplifying calculations in fluid dynamics and structural engineering",
          "Optimizing material usage in manufacturing processes",
        ],
      },
      limitations: {
        title: "Limitations and Considerations",
        list: [
          "The axis of rotation must not intersect the plane figure or curve",
          "The theorems assume a complete 360° rotation",
          "For partial rotations, the formula must be adjusted by replacing 2π with the angle of rotation",
          "The centroid of the figure or curve must be accurately determined for precise results",
        ],
      },
    },
    es: {
      title: "Teorema de Pappus",
      description: "Calcula volúmenes y áreas de superficie utilizando centroides de regiones planas.",
      backLink: "Volver a Aplicaciones",
      introduction:
        "El Teorema de Pappus, nombrado en honor al matemático griego Pappus de Alejandría, proporciona fórmulas elegantes para calcular volúmenes y áreas de superficie de sólidos de revolución utilizando el concepto de centroides. Estos teoremas simplifican cálculos complejos y ofrecen poderosas perspectivas sobre las propiedades de objetos tridimensionales.",
      firstTheorem: {
        title: "Primer Teorema de Pappus-Guldinus (Volumen)",
        description:
          "El volumen de un sólido de revolución generado al rotar una figura plana alrededor de un eje externo es igual al producto del área de la figura y la distancia recorrida por su centroide durante la rotación:",
        formula: "V = A \\cdot 2\\pi\\bar{d}",
        where: "donde:",
        whereDescription: [
          "V es el volumen del sólido de revolución",
          "A es el área de la figura plana que se está rotando",
          "\\bar{d} es la distancia desde el centroide de la figura al eje de rotación",
        ],
      },
      secondTheorem: {
        title: "Segundo Teorema de Pappus-Guldinus (Área de Superficie)",
        description:
          "El área de superficie de un sólido de revolución generado al rotar una curva plana alrededor de un eje externo es igual al producto de la longitud de la curva y la distancia recorrida por su centroide durante la rotación:",
        formula: "S = L \\cdot 2\\pi\\bar{d}",
        where: "donde:",
        whereDescription: [
          "S es el área de superficie del sólido de revolución",
          "L es la longitud de la curva que se está rotando",
          "\\bar{d} es la distancia desde el centroide de la curva al eje de rotación",
        ],
      },
      example: {
        title: "Ejemplo: Volumen de un Toro",
        problem:
          "Calcula el volumen de un toro (forma de dona) con una sección transversal circular de radio r = 2 unidades, donde la distancia desde el centro de la sección transversal al eje de rotación es R = 5 unidades.",
        solution: {
          title: "Solución:",
          step1: "1. Identifica la figura plana y su área:",
          step1Description: "La figura plana es un círculo con radio r = 2 unidades.",
          step1Formula: "A = \\pi r^2 = \\pi \\cdot 2^2 = 4\\pi \\text{ unidades cuadradas}",
          step2: "2. Identifica la distancia desde el centroide al eje de rotación:",
          step2Description:
            "El centroide de un círculo está en su centro, que está a R = 5 unidades del eje de rotación.",
          step2Formula: "\\bar{d} = R = 5 \\text{ unidades}",
          step3: "3. Aplica el Primer Teorema de Pappus-Guldinus:",
          step3Formula: "V = A \\cdot 2\\pi\\bar{d} = 4\\pi \\cdot 2\\pi \\cdot 5 = 40\\pi^2 \\text{ unidades cúbicas}",
          step4: "4. Calcula el valor numérico:",
          step4Formula: "V = 40\\pi^2 \\approx 40 \\cdot 9.87 \\approx 394.8 \\text{ unidades cúbicas}",
        },
      },
      applications: {
        title: "Aplicaciones",
        description: "El Teorema de Pappus tiene numerosas aplicaciones en matemáticas, ingeniería y física:",
        list: [
          "Cálculo de volúmenes y áreas de superficie de sólidos de revolución complejos",
          "Diseño y análisis de piezas mecánicas con simetría rotacional",
          "Simplificación de cálculos en dinámica de fluidos e ingeniería estructural",
          "Optimización del uso de materiales en procesos de fabricación",
        ],
      },
      limitations: {
        title: "Limitaciones y Consideraciones",
        list: [
          "El eje de rotación no debe intersectar la figura plana o curva",
          "Los teoremas asumen una rotación completa de 360°",
          "Para rotaciones parciales, la fórmula debe ajustarse reemplazando 2π con el ángulo de rotación",
          "El centroide de la figura o curva debe determinarse con precisión para obtener resultados exactos",
        ],
      },
    },
  }

  const currentContent = language === "es" ? content.es : content.en

  return (
    <div className="container py-8">
      <div className="flex justify-start mb-8">
        <Button variant="outline" asChild className="gap-1">
          <Link href="/topics/mathematics/integral-calculus-applications">
            <ArrowLeft className="h-4 w-4" />
            {currentContent.backLink}
          </Link>
        </Button>
      </div>

      <div className="space-y-8 max-w-4xl mx-auto">
        <div className="text-center">
          <h1 className="text-4xl font-bold mb-4">{currentContent.title}</h1>
          <p className="text-xl text-muted-foreground">{currentContent.description}</p>
        </div>

        <div>
          <p className="mb-6">{currentContent.introduction}</p>
        </div>

        <div className="bg-card p-6 rounded-lg border">
          <h2 className="text-2xl font-semibold mb-4">{currentContent.firstTheorem.title}</h2>
          <p className="mb-4">{currentContent.firstTheorem.description}</p>

          <div className="flex justify-center my-4">
            <MathDisplay math={currentContent.firstTheorem.formula} />
          </div>

          <div>
            <p className="font-medium mb-2">{currentContent.firstTheorem.where}</p>
            <ul className="list-disc pl-6 space-y-1">
              {currentContent.firstTheorem.whereDescription.map((item, index) => (
                <li key={index}>{item}</li>
              ))}
            </ul>
          </div>
        </div>

        <div className="bg-card p-6 rounded-lg border">
          <h2 className="text-2xl font-semibold mb-4">{currentContent.secondTheorem.title}</h2>
          <p className="mb-4">{currentContent.secondTheorem.description}</p>

          <div className="flex justify-center my-4">
            <MathDisplay math={currentContent.secondTheorem.formula} />
          </div>

          <div>
            <p className="font-medium mb-2">{currentContent.secondTheorem.where}</p>
            <ul className="list-disc pl-6 space-y-1">
              {currentContent.secondTheorem.whereDescription.map((item, index) => (
                <li key={index}>{item}</li>
              ))}
            </ul>
          </div>
        </div>

        <div className="bg-card p-6 rounded-lg border">
          <h2 className="text-2xl font-semibold mb-4">{currentContent.example.title}</h2>
          <p className="mb-4 font-medium">{currentContent.example.problem}</p>

          <div>
            <p className="font-semibold mb-2">{currentContent.example.solution.title}</p>

            <div className="space-y-4">
              <div>
                <p>{currentContent.example.solution.step1}</p>
                <p className="ml-4 my-2">{currentContent.example.solution.step1Description}</p>
                <div className="flex justify-center my-2">
                  <MathDisplay math={currentContent.example.solution.step1Formula} />
                </div>
              </div>

              <div>
                <p>{currentContent.example.solution.step2}</p>
                <p className="ml-4 my-2">{currentContent.example.solution.step2Description}</p>
                <div className="flex justify-center my-2">
                  <MathDisplay math={currentContent.example.solution.step2Formula} />
                </div>
              </div>

              <div>
                <p>{currentContent.example.solution.step3}</p>
                <div className="flex justify-center my-2">
                  <MathDisplay math={currentContent.example.solution.step3Formula} />
                </div>
              </div>

              <div>
                <p>{currentContent.example.solution.step4}</p>
                <div className="flex justify-center my-2">
                  <MathDisplay math={currentContent.example.solution.step4Formula} />
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="bg-card p-6 rounded-lg border">
          <h2 className="text-2xl font-semibold mb-4">{currentContent.applications.title}</h2>
          <p className="mb-4">{currentContent.applications.description}</p>
          <ul className="list-disc pl-6 space-y-1">
            {currentContent.applications.list.map((item, index) => (
              <li key={index}>{item}</li>
            ))}
          </ul>
        </div>

        <div className="bg-card p-6 rounded-lg border">
          <h2 className="text-2xl font-semibold mb-4">{currentContent.limitations.title}</h2>
          <ul className="list-disc pl-6 space-y-1">
            {currentContent.limitations.list.map((item, index) => (
              <li key={index}>{item}</li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  )
}
